name: Publish Artifact

on:
  workflow_call:
    inputs:
      concurrency_cancel:
        default: true
        description: "The concurrency cancel to use"
        required: false
        type: boolean
      concurrency_group:
        default: "publish_${{ github.ref }}"
        description: "The concurrency group to use"
        required: false
        type: string
      dockerhub_user:
        description: "The Docker Hub username"
        required: false
        default: "containifyci"
        type: string
      runs_on:
        default: "ubuntu-24.04"
        description: "The runner vm image to use for example ubuntu-24.04"
        required: false
        type: string
      tag_name:
        description: "Tag to release"
        required: true
        default: ""
        type: string
    secrets:
      CONTAINIFYCI_DOCKER_TOKEN:
        required: false

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: ${{ inputs.concurrency_cancel }}

permissions:
  contents: write # for checkout

env:
  GOMODCACHE: /home/runner/go/pkg/mod
  GOCACHE: /home/runner/go/pkg/mod/build-cache
  CONTAINIFYCI_CACHE: /home/runner/go/pkg/mod
  CONTAINIFYCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CONTAINIFYCI_FILE: .containifyci/containifyci.go
  CONTAINIFYCI_GITHUB_REF: refs/tags/${{ inputs.tag_name }}
  GORELEASER_CURRENT_TAG: ${{ inputs.tag_name }}

jobs:
  publish:
    name: Publish Artifact
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.tag_name }}
          fetch-depth: 0

      - name: Update major and minor release tags
        uses: rickstaa/action-update-semver@v1
        with:
          tag: ${{ inputs.tag_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: env.CONTAINIFYCI_DOCKER_TOKEN != null
        env:
          CONTAINIFYCI_DOCKER_TOKEN: ${{ secrets.CONTAINIFYCI_DOCKER_TOKEN }}
        with:
          username: ${{ inputs.dockerhub_user }}
          password: ${{ secrets.CONTAINIFYCI_DOCKER_TOKEN }}

      - name: Cache Go Mod
        uses: actions/cache@v4
        if: always()
        with:
          path: /home/runner/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
          save-always: true

      - name: Install Engine CI
        uses: jaxxstorm/action-install-gh-release@v1
        with:
          repo: containifyci/engine-ci
          # At the moment fetch latest release
          # version: ${{ inputs.version }}
          cache: true
          extension-matching: disable
          rename-to: engine-ci
          chmod: 0755

      - name: Release
        run: |
          engine-ci engine -t release
